// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSpxu-cXgIm25GrADgKl7qLcHorUqwyv0',
    appId: '1:100722415627:web:715909eac07651d6eb0f0e',
    messagingSenderId: '100722415627',
    projectId: 'lolteamd',
    authDomain: 'lolteamd.firebaseapp.com',
    databaseURL: 'https://lolteamd-default-rtdb.firebaseio.com',
    storageBucket: 'lolteamd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9bK5gAchOSiTaRhE3UPCvvVlun_zBo_Q',
    appId: '1:100722415627:android:51e8449c35deab2deb0f0e',
    messagingSenderId: '100722415627',
    projectId: 'lolteamd',
    databaseURL: 'https://lolteamd-default-rtdb.firebaseio.com',
    storageBucket: 'lolteamd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-MTdMIEtN3cwBnmT51r3e6twpGpCg3w',
    appId: '1:100722415627:ios:dd31db894e8e0108eb0f0e',
    messagingSenderId: '100722415627',
    projectId: 'lolteamd',
    databaseURL: 'https://lolteamd-default-rtdb.firebaseio.com',
    storageBucket: 'lolteamd.appspot.com',
    iosClientId: '100722415627-697oc6eucqolumjhj9ink24o5e636nsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lolTeamAppDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG-MTdMIEtN3cwBnmT51r3e6twpGpCg3w',
    appId: '1:100722415627:ios:dd31db894e8e0108eb0f0e',
    messagingSenderId: '100722415627',
    projectId: 'lolteamd',
    databaseURL: 'https://lolteamd-default-rtdb.firebaseio.com',
    storageBucket: 'lolteamd.appspot.com',
    iosClientId: '100722415627-697oc6eucqolumjhj9ink24o5e636nsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lolTeamAppDeneme',
  );
}
